# Generated by Django 6.0.1 on 2026-03-08 17:59

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos', validators=[photos.validators.FileSizeValidator(5)]),
        ),
    ]
